# .sops.yaml
keys:
  - &admin    age1jg3c7up285wumas8tm5l8utjv72u3pktw5eaz6flw0zxnsymecgqygtuvu 
  - &iroha    age19tgcepp6md56qxcc7an8g608eun6qnhv3y9gv9kghg8uym050umqp4zu9c
  - &yukino   age1tfakzrtjwgd52qv57ezm648e8tmunxtw6v0vmltnx5jn53u37fkqray347

creation_rules:
  # 只要是 secrets 目录下的文件，都同时加上这两把锁
  - path_regex: secrets[\\/].*
    key_groups:
      - age:
          - *admin
          - *iroha
          - *yukino
