# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
/*
  ===================================================================================
  Hardware Configuration for Host 'yukino'
  ===================================================================================
  此文件通常由 `nixos-generate-config` 自动生成，包含针对特定硬件的内核模块和引导配置。
  
  注意:
  1. 除非十分必要 (如手动添加内核模块)，否则尽量不要手动修改此文件。
  2. 文件系统挂载点通常在 `disko.nix` 中定义，此处主要关注硬件驱动支持。
*/
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # Initrd (Initial RAM Disk) 内核模块
  # 用于在挂载根文件系统之前加载必要的驱动 (如 SATA/NVMe 控制器, USB 支持等)
  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  
  # 额外的 initrd 模块 (手动指定)
  boot.initrd.kernelModules = [ ];
  
  # 系统运行时加载的内核模块
  boot.kernelModules = [ ];
  
  # 额外的内核模块包
  boot.extraModulePackages = [ ];

  # Swap 设备 (通常由 disko 管理，此处为空)
  swapDevices = [ ];

  # 设置主机平台架构 (x86_64-linux)
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
